keys: Avoid conflicts with `releasekey.x509.pem`
* Fixes the following error while trying to build with LineageOS 20

```
error: destination "releasekey.x509.pem" has two files
"vendor/lineage-priv/keys/releasekey.x509.pem" and
"vendor/lineage-priv/keys/releasekey.x509.pem"
```

Change-Id: I4955c4027ca884b2d7559cea2bca5d4c7ed6d4a3